export enum Language {
    Chinese = 'zh',
    Czech = 'cs',
    Dutch = 'nl',
    Finnish = 'fi',
    French = 'fr',
    German = 'de',
    Greek = 'el',
    Hungarian = 'hu',
    Italian = 'it',
    Japanese = 'ja',
    Korean = 'ko',
    Norwegian = 'no',
    Polish = 'pl',
    Romanian = 'ro',
    Russian = 'ru',
    Spanish = 'es',
}
