env:
    global:
        - CC_TEST_REPORTER_ID=$CODE_CLIMATE_ID

language: node_js
node_js:
    - '14'

addons:
    chrome: stable

cache:
    directories:
        - ./node_modules

install:
    - npm install

jobs:
    include:
        - name: master
          if: branch = master
          before_script:
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build
          script:
              - commitlint-travis
              - npm run eslint
              - npm run stylelint
              - npm run markdownlint
              - npm run test:coverage -- --no-progress --browsers=ChromeHeadlessCI
              # TODO: uncomment next line to enable e2e test on push via travis
              # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
              - npm run build
          after_script:
              - ./cc-test-reporter format-coverage -t lcov -o coverage/dominionizer/codeclimate.json coverage/dominionizer/lcov.info
              - ./cc-test-reporter upload-coverage -i coverage/dominionizer/codeclimate.json
        - name: release
          if: branch = release
          script:
              - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
              # TODO: add test coverage for e2e test on push via travis
              - npm run build

deploy:
    provider: pages:git
    github_token: $GITHUB_TOKEN
    local_dir: dist/dominionizer
    edge: true
    on:
        branch: release
