env:
    global:
        - CC_TEST_REPORTER_ID=$CODE_CLIMATE_ID

language: node_js
node_js:
    - '14'

addons:
    chrome: stable

cache:
    directories:
        - ./node_modules

install:
    - npm install

before_script:
    - npm install -g nyc
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - npm run eslint
    - npm run stylelint
    - npm run markdownlint
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    # TODO: uncomment next line to enable e2e test on push via travis
    # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - npm run build
    - nyc --reporter=lcov npm run test:coverage -- --no-progress --browsers=ChromeHeadlessCI

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist/dominionizer
    on:
        branch: master
