language: node_js
node_js:
    - '14'

addons:
    chrome: stable

cache:
    directories:
        - ./node_modules

install:
    - npm install

script:
    - npm run eslint
    - npm run stylelint
    - npm run markdownlint
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    # TODO: uncomment next line to enable e2e test on push via travis
    # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist/dominionizer
    on:
        branch: master
