name: Run linters

on:
    push:
        branches-ignore:
            - release

jobs:
    setup-linters:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  path: workspace

            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: |
                  cd workspace
                  npm ci

            - name: Cache workspace
              uses: actions/cache@v2
              with:
                  path: workspace
                  key: workspace-${{ github.sha }}

    commitlint:
        needs: setup-linters
        runs-on: ubuntu-latest
        steps:
            - name: Cache workspace
              uses: actions/cache@v2
              with:
                  path: workspace
                  key: workspace-${{ github.sha }}

            - name: Run commitlint
              run: |
                  cd workspace
                  npx --no-install commitlint --verbose --from ${{ github.event.push.before }} --to HEAD

    eslint:
        needs: setup-linters
        runs-on: ubuntu-latest
        steps:
            - name: Cache workspace
              uses: actions/cache@v2
              with:
                  path: workspace
                  key: workspace-${{ github.sha }}

            - name: Run eslint
              run: |
                  cd workspace
                  npm run eslint

    stylelint:
        needs: setup-linters
        runs-on: ubuntu-latest
        steps:
            - name: Cache workspace
              uses: actions/cache@v2
              with:
                  path: workspace
                  key: workspace-${{ github.sha }}

            - name: Run stylelint
              run: |
                  cd workspace
                  npm run stylelint

    markdownlint:
        needs: setup-linters
        runs-on: ubuntu-latest
        steps:
            - name: Cache workspace
              uses: actions/cache@v2
              with:
                  path: workspace
                  key: workspace-${{ github.sha }}

            - name: Run markdownlint
              run: |
                  cd workspace
                  npm run markdownlint
