name: Update release branch

on:
    push:
        tags:
            - 'v[0-9]+'

jobs:
    update-release-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Merge master into release
              uses: devmasx/merge-branch@v1.3.1
              with:
                  type: now
                  target_branch: release
                  github_token: ${{ secrets.UPDATE_RELEASE_BRANCH_TOKEN }}
