name: Update release branch

on:
    push:
        tags:
            - 'v[0-9]+'

jobs:
    update-release-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Rebase release branch
              run: |
                  git rebase --onto ${{ github.ref }} master
                  git push
